---
title: day5(面向对象2)
date: 2017-03-09 12:55:17
categories: Java
tags: java
---
# 内部类

----------
## 内部类访问规则
1. 内部类可以直接访问外部类中的成员，包括私有
    之所以可以直接访问外部类中的成员，是因为内部类中持有了 一个外部类的引用，格式：外部类名.this
2. 外部类要访问内部类，必须建立内部类对象。
	直接访问内部类中的成员
访问格式：
当内部类定义在外部类的成员位置上，就可以被成员修饰符所修饰。
比如，private：将内部类在外部类中进行封装。
	static：内部类就具备static的特性。
当内部类被static修饰后，只能直接访问外部类中的static成员，出现了访问局限。
在外部其他类中，如何访问内部类的非静态成员呢？
## 内部类定义的原则
当描述事物时，事物的内部还有事物，该事物用内部类来描述。因为内部事物在使用外部事物的内容。

内部类定义在局部时，
1. 不可以被成员修饰符修饰
2. 可以直接访问外部类中的成员，因为还持有外部类中的引用。但是不可以访问它所在的局部中的变量，只能访问被final修饰的局部变量  、
## 匿名内部类
1. 匿名内部类其实就是内部类的简写格式
2. 定义匿名内部类的前提：内部类必须是继承一个类或者实现接口。
3. 匿名内部类的格式：new 父类或者接口（）{定义子类的内容}
4. 其实匿名内部类就是一个匿名子类对象，而且这个对象有点胖。可以理解为带内容的对象
5. 匿名内部类中定义的方法最多不要超过三个

## 异常概述
异常：就是程序在运行时出现不正常的情况。
异常的由来：问题也是现实生活中一个具体的事物，也可以通过java的类的形式进行描述。并封装成对象。其实就是java对不正常情况进行描述后的对象体现
对于问题的划分：两种：一种是严重的问题，一种是不严重的问题

对于严重的，java通过Error类进行描述。
对于Error，一般不编写针对性的代码进行处理
对于非严重的，java通过Exception类进行描述。（可以使用针对性的处理方式进行处理 ）
## 异常try-catch
异常的处理：java提供了特有的语句进行处理
对捕获到的异常对象进行常见的方法操作。
String getMessage
## 异常声明throws
## 多异常处理
对多异常的处理。
1. 声明异常时，建议声明更为具体的异常。这样处理的可以更具体。
2. 对方声明几个异常，就对应有几个catch块。不要定义多余的catch块
	如果多个catch块中的异常出现继承关系，父类异常catch块放在最下面
建立在进行catch处理时，catch中一定要具体的处理方式。不要简单的定义一句e.peintStackTrace()，也不要简单的就书写一条输出语句。

## 自定义异常
项目中会出现特有的问题，而这些问题并未被java所描述并封装对象。所以对于这些特有的问题可以按照java对问题封装的思想。将特有的问题。进行自定义的异常封装。
当在函数内部出现了throw抛出异常对象，那么就必须要给对应的处理动作。
要么在内部try catch处理，要么在函数上声明让调用者处理。
发现打印的结果中只有异常的名称，缺没有异常的信息。
因为自定义的异常并未定义信息。
父类中已经把异常信息的操作都完成了。所以子类只要在构造时，将异常信息传递给父类通过super语句。那么直接就可以通过getMessage方法获取自定义的异常。

----------
自定义异常：必须是自定义类继承Exception。原因是：
异常体系有一个特点：因为异常类和异常对象都被抛出。他们都具备可抛性。这个可抛性是Throwable这个体系中的独有特点。只有这个体系中的类和对象才可以被throw和throws操作。
## throws 和throw的区别：throws使用在函数上。throw使用在函数内。
throws后面跟的异常类，可以跟多个。用逗号隔开。throw后面跟的是异常对象。
## RuntimeException运行时异常。
如果在函数内抛出该异常，函数上可以不用声明，编译一样通过。
如果在函数上声明了该异常。调用者可以不用进行处理。编译一样通过。
之所以不用在函数声明，是因为不需要让调用者处理，当该异常发生，希望程序停止。因为在运行时，出现了无法继续运算的情况，希望停止程序后，对代码尽心修正。
自定义异常时，如果该异常的发生，无法再继续进行运算，就让自定义异常继承RuntimeException
对于异常分两种：
1. 编译时被检测的异常。
2. 编译时不被检测的异常（运行时异常。RuntimeException以及其子类）
